services:
  - type: web
    name: skyguard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: CAMERA_URL
        value: rtsp://admin:123456@192.168.0.109:554/stream1
